### ISSUE TITLE
ReferenceError: Can't find variable: AV_ga

### ISSUE THREAD

**Issue by IgnacioGaldames** [CreativeSDK/web-getting-started-samples#13]
f — editor.js:1:24993ReferenceError: Can't find variable: AV_ga

I try the code in the page: https://creativesdk.adobe.com/docs/web/#/articles/example/index.html, and then copying this one and running nom install, but it gives the same error.

**Comment by rathishubham7** [comment]
how did you solve it ? i'm getting the same error .
